---
{{- include "bjw-s.common.loader.init" . }}

{{- define "app.hardcodedValues" -}}
initContainers:
# -- Configures an initContainer that copies the configmap to the AdGuardHome conf directory
# It does NOT overwrite when the file already exists.
  copy-configmap:
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
    - "sh"
    - "-c"
    - |
      if [ ! -f /opt/adguardhome/conf/AdGuardHome.yaml ]; then
        mkdir -p /opt/adguardhome/conf
        cp /tmp/AdGuardHome.yaml /opt/adguardhome/conf/AdGuardHome.yaml
      fi
    volumeMounts:
    - name: configmap
      mountPath: /tmp/AdGuardHome.yaml
      subPath: AdGuardHome.yaml
    - name: config
      mountPath: /opt/adguardhome/conf
    securityContext:
      runAsUser: 0
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "app.hardcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
