apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: bjw-s
  pass_credentials_all: false
  password: ""
  url: https://bjw-s-labs.github.io/helm-charts
  username: ""
