---
{{- include "bjw-s.common.loader.init" . }}

{{- define "qbittorrent.hardcodedValues" -}}
securityContext:
#  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "qbittorrent.hardcodedValues" . | fromYaml) -}}


{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
