---
apiVersion: v2
description: Deluge Torrent Client & Webinterface
name: deluge
version: 1.2.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: nold
    email: nold@gnu.one
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
