{{- if .Values.deluge.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}-ingress"
  labels:
    app: {{ .Chart.Name }}
spec:
  rules:
  - host: {{ .Values.deluge.ingress.vhost }}
    http:
      paths:
      - backend:
          service:
            name: "{{ .Chart.Name }}-service"
            port:
              number: 8112
        pathType: ImplementationSpecific
        path: {{ .Values.deluge.ingress.path | default "/" }}
{{- end }}
