---
apiVersion: v2
description: QBittorrent
name: qbittorrent
version: 1.0.0
kubeVersion: ">=1.22.0-0"
sources:
  - https://github.com/qbittorrent/qBittorrent
home: https://github.com/lib42/charts
icon: https://avatars.githubusercontent.com/u/2131270
maintainers:
  - name: nold
    email: nold@gnu.one
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.7.3
