# BorgServer on Kubernetes
image:
  repository: lib42/borgserver
  tag: latest

  init_repository: lib42/borgserver
  init_tag: latest

# Right now only hostPort & hostPath supported
hostPort: 2222
hostPath: /data/backup/lan
borg:
  admin: ""
  serve_args: "--append-only"
  #data_dir: /backup

# Add your client pubkeys here:
clients: []
#  - name: admin
#    isAdmin: true
#    type: ssh-rsa
#    key: AAAABfC4LL0S70F9BbnTx3uYJfSVI7b/HAR....
#  - name: another-client
#    type: ssh-rsa
#    key: AAAAB3NzaC1yc2EAAAADAQABAAABAQClJ8m1....

terminationGracePeriodSeconds: 100
