# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json

controllers:
  main:
    containers:
      main:
        image:
          repository: adguard/adguardhome
          tag: v0.107.66
          pullPolicy: IfNotPresent

        env:
          # -- Set the container timezone
          TZ: UTC

ingress:
  main:
    enabled: false
    annotations: {}
    hosts:
    - host: adguard.home
      paths:
      - path: /
        pathType: Prefix
        service:
          identifier: main
          port: http

    tls: []
    # - secretName: adguard-tls
    #   hosts:
    #   - adguard.home

service:
  main:
    ports:
      http:
        port: 3000

  dns:
    controller: main
    type: LoadBalancer
    annotations: {}
    ports:
      dns-https:
        port: 443
        protocol: TCP
      dns-tcp:
        port: 53
        protocol: TCP
      dns-udp:
        port: 53
        protocol: UDP
      tls-tcp:
        port: 853
        protocol: TCP

persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /opt/adguardhome/conf

  data:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
    globalMounts:
      - path: /opt/adguardhome/work