---
{{- include "bjw-s.common.loader.init" . }}

{{- define "app.hardcodedValues" -}}
persistence:
  config:
    name: {{ include "bjw-s.common.lib.chart.names.fullname" . -}}-config
    enabled: true
    type: configMap
    mountPath: /etc/squid/squid.conf
    subPath: squid.conf

  varrun:
    enabled: true
    type: emptyDir
    mountPath: /var/run

podSecurityContext:
  runAsUser: 31
  runAsGroup: 31
  fsGroup: 31

securityContext:
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "app.hardcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
