---
steps:
  pr-lint:
    image: alpine/helm@sha256:f27b82cfca2e7575d0529a1235694fa1411f1836cc417ec05f1ebce7c809bed4
    environment:
      USE_SSH: "true"
      GIT_USER: $DRONE_COMMIT_AUTHOR
    commands:
    - git fetch --all
    - "export CHART=$(git diff --name-only origin/main | awk -F/ '/^charts/ { print $$2 }' | head -n1)"
    - "echo Chart: $${CHART}"
    - |
      RET=0
      if [ -n "$$CHART" ] ; then
        cd charts/$${CHART}
        helm dependency build
        helm lint
        RET=$?
      fi
      exit $$RET
    when:
      - event: [ "pull_request" ]
        path:
        - charts/**
