---
steps:
  pr-lint:
    image: alpine/helm@sha256:c6d8088ddb279625a2e1ca3b08b22c18c946d1f65c8b810f28f1597435a1134c
    environment:
      USE_SSH: "true"
      GIT_USER: $DRONE_COMMIT_AUTHOR
    commands:
    - git fetch --all
    - "export CHART=$(git diff --name-only origin/main | awk -F/ '/^charts/ { print $$2 }' | head -n1)"
    - "echo Chart: $${CHART}"
    - |
      RET=0
      if [ -n "$$CHART" ] ; then
        cd charts/$${CHART}
        helm dependency build
        helm lint
        RET=$?
      fi
      exit $$RET
    when:
      - event: [ "pull_request" ]
        path:
        - charts/**
