---
steps:
  pr-lint:
    image: alpine/helm@sha256:c8c6274c07a30c700140e3651330bf6db87fd44b9335ae68a39333391a891b51
    environment:
      USE_SSH: "true"
      GIT_USER: $DRONE_COMMIT_AUTHOR
    commands:
    - git fetch --all
    - "export CHART=$(git diff --name-only origin/main | awk -F/ '/^charts/ { print $$2 }' | head -n1)"
    - "echo Chart: $${CHART}"
    - |
      RET=0
      if [ -n "$$CHART" ] ; then
        cd charts/$${CHART}
        helm dependency build
        helm lint
        RET=$?
      fi
      exit $$RET
    when:
      - event: [ "pull_request" ]
        path:
        - charts/**
