---
pipeline:
  helm-repo:
    image: quay.io/helmpack/chart-releaser
    commands:
    - mkdir -p ~/.config/helm
    - cp .helmrepos.yaml ~/.config/helm/repositories.yaml

    - cr package charts/*
    - cr upload --owner lib42 --git-repo charts --token $${GH_TOKEN}
    - cr index --owner lib42 --git-repo charts --token $${GH_TOKEN} --pages-branch repo --package-path .cr-release-packages --index-path index.yaml --charts-repo https://lib42.github.io/charts --push
    when:
      - event: push
        branch: main
        path:
        - charts/**
        - .woodpecker/release.yml
      - event: [ "manual", "cron" ]
    secrets: [ "gh_token" ]
