---
pipeline:
  helm-repo:
    image: quay.io/helmpack/chart-releaser
    commands:
    - git config --global user.email "noreply@lib42.github.io"
    - git config --global user.name "Woodpecker-CI"
    - mkdir -p ~/.config/helm
    - cp .helmrepos.yaml ~/.config/helm/repositories.yaml

    - cr package charts/*
    - cr upload --owner lib42 --git-repo charts --token $${GH_TOKEN} --skip-existing

    - git fetch --all
    - git checkout origin/repo

    - cr index --owner lib42 --git-repo charts --token $${GH_TOKEN} --pages-branch repo --package-path .cr-release-packages --index-path index.yaml --push
    when:
      - event: push
        branch: main
        path:
        - charts/**
        - .woodpecker/release.yml
      - event: [ "manual", "cron" ]
    secrets: [ "gh_token" ]
